<?php
/*
 * Auto-generated Indonesian translation overrides (users portal).
 * Generated by translate.googleapis.com (client=gtx).
 */

$l['all']['ID'] = 'ID';
$l['all']['Status'] = 'Status';
$l['all']['Global'] = 'Global';
$l['ContactInfo']['Email'] = 'E-mail';
$l['helpPage']['billinvoicelist'] = '';
$l['helpPage']['billmain'] = '';
